version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6969:6969
    volumes:
      - ./app:/code/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME = user
      - MONGO_INITDB_ROOT_PASSWORD = pass12345
      - MONGO_INITDB_DATABASE = db0
    ports:
      - "27013:27017"
    volumes:
      - .db_data:/data/db


